name: econ
channels:
  - nvidia
  - pytorch
  - conda-forge
  - fvcore
  - iopath
  - bottler
  - defaults
dependencies:
  - python=3.8
  - pytorch-cuda=11.3
  - fvcore
  - iopath
  - cupy
  - cython
  - pip

