name: econ
channels:
  - pytorch
  - nvidia
  - conda-forge
  - fvcore
  - iopath
  - bottler
  - defaults
dependencies:
  - python=3.8
  - pytorch-cuda=11.6
  - pytorch=1.13.1
  - nvidiacub
  - torchvision=0.14.1
  - pytorch-lightning=1.9.0
  - fvcore
  - iopath
  - pyembree
  - cupy
  - cython
  - pip
