name: econ
channels:
  - pytorch
  - nvidia
  - conda-forge
  - fvcore
  - iopath
  - bottler
  - defaults
dependencies:
  - python=3.8
  - pytorch-cuda=11.6
  - pytorch=1.13.1
  - nvidiacub
  - torchvision=0.14.1
  - fvcore=0.1.5.post20221221
  - iopath=0.1.10
  - pyembree=0.1.6
  - cupy=12.3.0
  - cython=3.0.11
  - pip=24.3.1
